// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateConversationData, CreateConversationErrors, CreateConversationResponses, DeleteConversationData, DeleteConversationErrors, DeleteConversationResponses, DeleteDocumentData, DeleteDocumentErrors, DeleteDocumentResponses, DownloadDocumentData, DownloadDocumentErrors, DownloadDocumentResponses, GetConversationData, GetConversationErrors, GetConversationResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, GetDocumentsChunkData, GetDocumentsChunkErrors, GetDocumentsChunkResponses, HealthAppData, HealthAppResponses, HealthCosData, HealthCosResponses, HealthDbData, HealthDbResponses, ListConversationsData, ListConversationsErrors, ListConversationsResponses, ListDocumentsChunksData, ListDocumentsChunksErrors, ListDocumentsChunksResponses, ListDocumentsData, ListDocumentsErrors, ListDocumentsResponses, RetryDocumentData, RetryDocumentErrors, RetryDocumentResponses, StreamChatData, StreamChatErrors, StreamChatResponses, UploadDocumentData, UploadDocumentErrors, UploadDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const healthApp = <ThrowOnError extends boolean = false>(options?: Options<HealthAppData, ThrowOnError>) => (options?.client ?? client).get<HealthAppResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Health Db
 */
export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>) => (options?.client ?? client).get<HealthDbResponses, unknown, ThrowOnError>({ url: '/api/health/db', ...options });

/**
 * Health Cos
 */
export const healthCos = <ThrowOnError extends boolean = false>(options?: Options<HealthCosData, ThrowOnError>) => (options?.client ?? client).get<HealthCosResponses, unknown, ThrowOnError>({ url: '/api/health/cos', ...options });

/**
 * List Documents
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentsData, ThrowOnError>) => (options?.client ?? client).get<ListDocumentsResponses, ListDocumentsErrors, ThrowOnError>({ url: '/api/documents', ...options });

/**
 * Upload Document
 */
export const uploadDocument = <ThrowOnError extends boolean = false>(options: Options<UploadDocumentData, ThrowOnError>) => (options.client ?? client).post<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Document
 */
export const deleteDocument = <ThrowOnError extends boolean = false>(options: Options<DeleteDocumentData, ThrowOnError>) => (options.client ?? client).delete<DeleteDocumentResponses, DeleteDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Get Document
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>) => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Retry Document
 */
export const retryDocument = <ThrowOnError extends boolean = false>(options: Options<RetryDocumentData, ThrowOnError>) => (options.client ?? client).post<RetryDocumentResponses, RetryDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Download Document
 */
export const downloadDocument = <ThrowOnError extends boolean = false>(options: Options<DownloadDocumentData, ThrowOnError>) => (options.client ?? client).get<DownloadDocumentResponses, DownloadDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}/file', ...options });

/**
 * List Documents Chunks
 */
export const listDocumentsChunks = <ThrowOnError extends boolean = false>(options: Options<ListDocumentsChunksData, ThrowOnError>) => (options.client ?? client).get<ListDocumentsChunksResponses, ListDocumentsChunksErrors, ThrowOnError>({ url: '/api/documents/{document_id}/chunks', ...options });

/**
 * Get Document Chunk
 */
export const getDocumentsChunk = <ThrowOnError extends boolean = false>(options: Options<GetDocumentsChunkData, ThrowOnError>) => (options.client ?? client).get<GetDocumentsChunkResponses, GetDocumentsChunkErrors, ThrowOnError>({ url: '/api/documents/{document_id}/chunks/{chunk_id}', ...options });

/**
 * 按更新事件倒序分页列出所有会话
 */
export const listConversations = <ThrowOnError extends boolean = false>(options?: Options<ListConversationsData, ThrowOnError>) => (options?.client ?? client).get<ListConversationsResponses, ListConversationsErrors, ThrowOnError>({ url: '/api/conversations', ...options });

/**
 * Create Conversation
 */
export const createConversation = <ThrowOnError extends boolean = false>(options: Options<CreateConversationData, ThrowOnError>) => (options.client ?? client).post<CreateConversationResponses, CreateConversationErrors, ThrowOnError>({
    url: '/api/conversations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Conversation
 */
export const deleteConversation = <ThrowOnError extends boolean = false>(options: Options<DeleteConversationData, ThrowOnError>) => (options.client ?? client).delete<DeleteConversationResponses, DeleteConversationErrors, ThrowOnError>({ url: '/api/conversations/{conversation_id}', ...options });

/**
 * Get Conversation
 */
export const getConversation = <ThrowOnError extends boolean = false>(options: Options<GetConversationData, ThrowOnError>) => (options.client ?? client).get<GetConversationResponses, GetConversationErrors, ThrowOnError>({ url: '/api/conversations/{conversation_id}', ...options });

/**
 * Stream Chat
 */
export const streamChat = <ThrowOnError extends boolean = false>(options: Options<StreamChatData, ThrowOnError, unknown>) => (options.client ?? client).sse.post<StreamChatResponses, StreamChatErrors, ThrowOnError>({
    url: '/api/conversations/{conversation_id}/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
