// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AgentStep
 */
export type AgentStep = {
    /**
     * Round
     */
    round: number;
    /**
     * Action
     */
    action: 'initial' | 'proceed' | 'rewrite_query' | 'switch_route' | 'refuse';
    /**
     * Reason
     */
    reason: string;
    /**
     * Route
     */
    route: 'original' | 'rewrite' | 'hyde' | 'multi_query';
    /**
     * Query
     */
    query: string;
    /**
     * Retrieved Count
     */
    retrieved_count?: number | null;
    /**
     * Top Score
     */
    top_score?: number | null;
    /**
     * Sufficient
     */
    sufficient?: boolean | null;
};

/**
 * Body_upload_document
 */
export type BodyUploadDocument = {
    /**
     * File
     *
     * 待上传文档（PDF/DOCX/MARKDOWN/HTML）
     */
    file: Blob | File;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Question
     */
    question: string;
};

/**
 * CitationRead
 */
export type CitationRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Document Id
     */
    document_id?: string | null;
    /**
     * Chunk Id
     */
    chunk_id?: string | null;
    /**
     * Document Name
     */
    document_name: string;
    /**
     * Page No
     */
    page_no?: number | null;
    /**
     * Quote
     */
    quote: string;
    retrieval_meta?: RetrievalMeta | null;
};

/**
 * ConversationCreate
 */
export type ConversationCreate = {
    /**
     * Title
     */
    title?: string;
};

/**
 * ConversationDetail
 */
export type ConversationDetail = {
    conversation: ConversationRead;
    /**
     * Message
     */
    message: Array<MessageRead>;
};

/**
 * ConversationRead
 */
export type ConversationRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentChunkDetail
 */
export type DocumentChunkDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Content
     */
    content: string;
    /**
     * Page No
     */
    page_no?: number | null;
    /**
     * Section Path
     */
    section_path?: string | null;
    /**
     * Char Count
     */
    char_count: number;
    /**
     * Chunk Hash
     */
    chunk_hash: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DocumentChunkListResponse
 */
export type DocumentChunkListResponse = {
    /**
     * Items
     */
    items: Array<DocumentChunkRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    stats?: DocumentChunkStats | null;
};

/**
 * DocumentChunkRead
 */
export type DocumentChunkRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Page No
     */
    page_no?: number | null;
    /**
     * Section Path
     */
    section_path?: string | null;
    /**
     * Content Excerpt
     */
    content_excerpt: string;
    /**
     * Char Count
     */
    char_count: number;
    /**
     * Chunk Hash
     */
    chunk_hash: string;
};

/**
 * DocumentChunkStats
 */
export type DocumentChunkStats = {
    /**
     * Total
     */
    total: number;
    /**
     * Avg Length
     */
    avg_length: number;
    /**
     * Min Length
     */
    min_length: number;
    /**
     * Max Length
     */
    max_length: number;
};

/**
 * DocumentListResponse
 */
export type DocumentListResponse = {
    /**
     * Items
     */
    items: Array<DocumentRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * DocumentRead
 */
export type DocumentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * File Hash
     */
    file_hash: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Status
     */
    status: 'uploading' | 'parsing' | 'indexing' | 'ready' | 'failed';
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
    /**
     * Status
     */
    status: 'ok' | 'error' | 'not_configured';
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * MessageRead
 */
export type MessageRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Citations
     */
    citations?: Array<CitationRead>;
    query_route?: QueryRouteRead | null;
    /**
     * Agent Steps
     */
    agent_steps?: Array<AgentStep> | null;
};

/**
 * QueryRouteRead
 */
export type QueryRouteRead = {
    /**
     * Route
     */
    route: 'original' | 'rewrite' | 'hyde' | 'multi_query';
    /**
     * Query
     */
    query: string;
    /**
     * Rewritten Query
     */
    rewritten_query?: string | null;
    /**
     * Hyde Answer
     */
    hyde_answer?: string | null;
    /**
     * Multi Querys
     */
    multi_querys?: Array<string> | null;
};

/**
 * RetrievalMeta
 */
export type RetrievalMeta = {
    /**
     * Sources
     */
    sources?: Array<string>;
    /**
     * Vector Rank
     */
    vector_rank?: number | null;
    /**
     * Vector Score
     */
    vector_score?: number | null;
    /**
     * Keyword Rank
     */
    keyword_rank?: number | null;
    /**
     * Keyword Score
     */
    keyword_score?: number | null;
    /**
     * Rrf Score
     */
    rrf_score?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthAppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthAppResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthAppResponse = HealthAppResponses[keyof HealthAppResponses];

export type HealthDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/db';
};

export type HealthDbResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthDbResponse = HealthDbResponses[keyof HealthDbResponses];

export type HealthCosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/cos';
};

export type HealthCosResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthCosResponse = HealthCosResponses[keyof HealthCosResponses];

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Status
         *
         * 按文档状态筛选
         */
        status?: 'uploading' | 'parsing' | 'indexing' | 'ready' | 'failed' | null;
    };
    url: '/api/documents';
};

export type ListDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentListResponse;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    path?: never;
    query?: never;
    url: '/api/documents';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    201: DocumentRead;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type DeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}';
};

export type DeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDocumentResponse = DeleteDocumentResponses[keyof DeleteDocumentResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}';
};

export type GetDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type RetryDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}';
};

export type RetryDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryDocumentError = RetryDocumentErrors[keyof RetryDocumentErrors];

export type RetryDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type RetryDocumentResponse = RetryDocumentResponses[keyof RetryDocumentResponses];

export type DownloadDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Download
         *
         * 1=强制下载 0=尝试内联预览
         */
        download?: number;
    };
    url: '/api/documents/{document_id}/file';
};

export type DownloadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadDocumentError = DownloadDocumentErrors[keyof DownloadDocumentErrors];

export type DownloadDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDocumentsChunksData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/documents/{document_id}/chunks';
};

export type ListDocumentsChunksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsChunksError = ListDocumentsChunksErrors[keyof ListDocumentsChunksErrors];

export type ListDocumentsChunksResponses = {
    /**
     * Successful Response
     */
    200: DocumentChunkListResponse;
};

export type ListDocumentsChunksResponse = ListDocumentsChunksResponses[keyof ListDocumentsChunksResponses];

export type GetDocumentsChunkData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}/chunks/{chunk_id}';
};

export type GetDocumentsChunkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentsChunkError = GetDocumentsChunkErrors[keyof GetDocumentsChunkErrors];

export type GetDocumentsChunkResponses = {
    /**
     * Successful Response
     */
    200: DocumentChunkDetail;
};

export type GetDocumentsChunkResponse = GetDocumentsChunkResponses[keyof GetDocumentsChunkResponses];

export type CreateConversationData = {
    body: ConversationCreate;
    path?: never;
    query?: never;
    url: '/api/conversations';
};

export type CreateConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationError = CreateConversationErrors[keyof CreateConversationErrors];

export type CreateConversationResponses = {
    /**
     * Successful Response
     */
    201: ConversationRead;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type GetConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}';
};

export type GetConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationError = GetConversationErrors[keyof GetConversationErrors];

export type GetConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type StreamChatData = {
    body: ChatRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/chat';
};

export type StreamChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatError = StreamChatErrors[keyof StreamChatErrors];

export type StreamChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
