"""version2

Revision ID: 26cdc5d1768c
Revises: 31e6ab97144d
Create Date: 2026-09-19 01:57:33.605087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cdc5d1768c'
down_revision: Union[str, Sequence[str], None] = '31e6ab97144d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_tasks_document_created'), table_name='ingestion_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingestion_tasks_document_created'), 'ingestion_tasks', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
