"""add ingestion tasks table and documnent version

Revision ID: 31e6ab97144d
Revises: 8c2d4d7d66b9
Create Date: 2026-09-18 23:04:46.889903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e6ab97144d'
down_revision: Union[str, Sequence[str], None] = '8c2d4d7d66b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_tasks_document_id'), 'ingestion_tasks', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_ingestion_tasks_document_created',"ingestion_tasks", ["document_id",sa.text("created_at DESC")])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'version')
    op.drop_index(op.f('ix_ingestion_tasks_document_id'), table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    # ### end Alembic commands ###
