"""change the column name

Revision ID: 4b146009581d
Revises: 617de3912dbc
Create Date: 2026-09-17 00:31:30.472171

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b146009581d'
down_revision: Union[str, Sequence[str], None] = '617de3912dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=False)
    op.add_column('evaluation_items', sa.Column('expected_answer', sa.Text(), nullable=False))
    op.add_column('evaluation_items', sa.Column('expected_document_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('evaluation_items', sa.Column('expected_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('evaluation_items', 'excepcted_document_names')
    op.drop_column('evaluation_items', 'excepcted_answer')
    op.drop_column('evaluation_items', 'excepcted_keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_items', sa.Column('excepcted_keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('evaluation_items', sa.Column('excepcted_answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('evaluation_items', sa.Column('excepcted_document_names', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('evaluation_items', 'expected_keywords')
    op.drop_column('evaluation_items', 'expected_document_names')
    op.drop_column('evaluation_items', 'expected_answer')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=True)
    # ### end Alembic commands ###
