"""add evaluate on tables

Revision ID: 617de3912dbc
Revises: aa3432276741
Create Date: 2026-09-14 20:10:51.554390

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '617de3912dbc'
down_revision: Union[str, Sequence[str], None] = 'aa3432276741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('dataset_name', sa.String(length=128), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_completed', sa.Integer(), nullable=False),
    sa.Column('progress_failed', sa.Integer(), nullable=False),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('citation_hit_rate', sa.Float(), nullable=True),
    sa.Column('refusal_accuracy', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_first_token_latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('excepcted_answer', sa.Text(), nullable=False),
    sa.Column('excepcted_document_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excepcted_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('should_refuse', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_answer', sa.Text(), nullable=False),
    sa.Column('actual_refused', sa.Boolean(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_chunks_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_route', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verify_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('first_token_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('citation_hit', sa.Boolean(), nullable=True),
    sa.Column('refusal_correct', sa.Boolean(), nullable=False),
    sa.Column('is_bad_case', sa.Boolean(), nullable=False),
    sa.Column('bad_case_category', sa.String(length=64), nullable=True),
    sa.Column('bad_case_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_items_run_id'), 'evaluation_items', ['run_id'], unique=False)
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.alter_column('document_chunks', 'content_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=False,
               existing_server_default=sa.Computed("to_tsvector('chinese_zh'::regconfig, content)", persisted=True))
    op.drop_index(op.f('ix_document_chunks_embeding_hnsw'), table_name='document_chunks', postgresql_ops={'embeding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('document_chunks', 'embeding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embeding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False))
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_embeding_hnsw'), 'document_chunks', ['embeding'], unique=False, postgresql_ops={'embeding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'content_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=True,
               existing_server_default=sa.Computed("to_tsvector('chinese_zh'::regconfig, content)", persisted=True))
    op.drop_column('document_chunks', 'embedding')
    op.drop_index(op.f('ix_evaluation_items_run_id'), table_name='evaluation_items')
    op.drop_table('evaluation_items')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
