"""修改了一些键的名字

Revision ID: c4d973a2571e
Revises: fdfba1dc8d26
Create Date: 2026-09-08 13:48:12.398642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d973a2571e'
down_revision: Union[str, Sequence[str], None] = 'fdfba1dc8d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.drop_column('document_chunks', 'chunk_size')
    op.add_column('documents', sa.Column('cos_object_key', sa.String(length=512), nullable=False))
    op.drop_column('documents', 'cos_object')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cos_object', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('documents', 'cos_object_key')
    op.add_column('document_chunks', sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('document_chunks', 'chunk_index')
    # ### end Alembic commands ###
